import { createClient } from "npm:@supabase/supabase-js@2";
import { XMLParser } from "npm:fast-xml-parser@4.5.0";

export const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";
export const admin = createClient(SUPABASE_URL, SERVICE_ROLE, {auth:{persistSession:false,autoRefreshToken:false}});
export const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type, x-client-info, apikey","Access-Control-Allow-Methods":"GET, POST, PATCH, DELETE, OPTIONS","Cache-Control":"no-store"};
export function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}})}
export function routePath(req:Request){const p=new URL(req.url).pathname,m="/app-api",i=p.indexOf(m);return i>=0?p.slice(i+m.length)||"/":p}
export function normEmail(v:unknown){return String(v||"").trim().toLowerCase()}
export function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=320}
export function validUrl(v:string){try{const u=new URL(v);return["http:","https:"].includes(u.protocol)&&!u.username&&!u.password}catch{return false}}
export function validTimezone(v:string){try{new Intl.DateTimeFormat("en-US",{timeZone:v}).format(new Date());return true}catch{return false}}
function hex(b:Uint8Array){return Array.from(b).map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function sha256(v:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))))}
function token(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function code(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(a[0]%1_000_000).padStart(6,"0")}
async function codeHash(email:string,c:string){return sha256(`${SERVICE_ROLE}:${email}:${c}`)}
async function mailCode(email:string,c:string){
  if(!RESEND_API_KEY)throw new Error("Email service is not configured.");
  const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:"Morning Reader <reader@antonioskilton.com>",to:[email],subject:`${c} is your Morning Reader code`,text:`Your Morning Reader sign-in code is ${c}. It expires in 10 minutes.`,html:`<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif"><p>Your Morning Reader sign-in code is:</p><p style="font-size:34px;font-weight:700;letter-spacing:6px">${c}</p><p>It expires in 10 minutes.</p></body></html>`})});
  if(!r.ok)throw new Error(`Email provider error (${r.status}): ${(await r.text()).slice(0,250)}`);
}
export async function requestCode(email:string){const since=new Date(Date.now()-600_000).toISOString();const{count}=await admin.from("login_codes").select("id",{count:"exact",head:true}).eq("email",email).gte("created_at",since);if((count||0)>=5)throw Object.assign(new Error("Too many codes requested. Try again in a few minutes."),{status:429});const c=code(),expires=new Date(Date.now()+600_000).toISOString();const{data,error}=await admin.from("login_codes").insert({email,code_hash:await codeHash(email,c),expires_at:expires}).select("id").single();if(error)throw error;try{await mailCode(email,c)}catch(e){await admin.from("login_codes").delete().eq("id",data.id);throw e}}
export async function verifyCode(email:string,c:string){const{data:login,error}=await admin.from("login_codes").select("*").eq("email",email).is("consumed_at",null).gt("expires_at",new Date().toISOString()).lt("attempts",5).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!login)throw Object.assign(new Error("That code has expired. Request a new one."),{status:401});if(await codeHash(email,c)!==login.code_hash){await admin.from("login_codes").update({attempts:login.attempts+1}).eq("id",login.id);throw Object.assign(new Error("That code is not correct."),{status:401})}await admin.from("login_codes").update({consumed_at:new Date().toISOString()}).eq("id",login.id);const{data:user,error:userError}=await admin.from("app_users").upsert({email},{onConflict:"email"}).select("id,email").single();if(userError)throw userError;const{data:settings}=await admin.from("user_settings").select("user_id").eq("user_id",user.id).maybeSingle();if(!settings)await admin.from("user_settings").insert({user_id:user.id,timezone:"America/Los_Angeles",delivery_time:"06:00:00"});const{count}=await admin.from("sections").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("archived_at",null);if(!count)await admin.from("sections").insert({user_id:user.id,name:"Reading",position:0});const raw=token(),expiresAt=new Date(Date.now()+30*86400_000).toISOString();const{error:se}=await admin.from("sessions").insert({user_id:user.id,token_hash:await sha256(raw),expires_at:expiresAt});if(se)throw se;return{raw,expiresAt,user}}
export async function auth(req:Request){const h=req.headers.get("authorization")||"",raw=h.startsWith("Bearer ")?h.slice(7).trim():"";if(!raw)return null;const{data,error}=await admin.from("sessions").select("id,user_id,app_users(id,email)").eq("token_hash",await sha256(raw)).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(error||!data)return null;await admin.from("sessions").update({last_seen_at:new Date().toISOString()}).eq("id",data.id);const u:any=Array.isArray((data as any).app_users)?(data as any).app_users[0]:(data as any).app_users;return{sessionId:data.id,user:{id:data.user_id,email:u?.email||""}}}
export async function dashboard(userId:string,email:string){const[s,se,fe,di,jo]=await Promise.all([admin.from("user_settings").select("*").eq("user_id",userId).single(),admin.from("sections").select("*").eq("user_id",userId).is("archived_at",null).order("position").order("created_at"),admin.from("feeds").select("*").eq("user_id",userId).is("archived_at",null).order("created_at"),admin.from("digests").select("id,section_id,status,article_count,error,created_at,sent_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(25),admin.from("digest_jobs").select("id,reason,status,result,error,created_at,started_at,finished_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(15)]);if(s.error)throw s.error;const sections=(se.data||[]).map((x:any)=>({...x,feeds:(fe.data||[]).filter((f:any)=>f.section_id===x.id)}));return{user:{id:userId,email},settings:s.data,sections,digests:di.data||[],jobs:jo.data||[],sender_email:"reader@antonioskilton.com"}}
export async function nextRun(tz:string,time:string){const{data,error}=await admin.rpc("next_delivery_at",{p_timezone:tz,p_time:time.length===5?`${time}:00`:time,p_from:new Date().toISOString()});if(error)throw error;return data}
function isPrivateV4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return false;const[a,b]=p;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}
function isPrivateV6(ip:string){const x=ip.toLowerCase();return x==="::1"||x==="::"||x.startsWith("fc")||x.startsWith("fd")||x.startsWith("fe8")||x.startsWith("fe9")||x.startsWith("fea")||x.startsWith("feb")}
async function assertPublic(u:URL){const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||isPrivateV4(h)||isPrivateV6(h))throw new Error("Private network URLs are not allowed.");if(!/^\d+\.\d+\.\d+\.\d+$/.test(h)&&!h.includes(":")){const ips=[...await Deno.resolveDns(h,"A").catch(()=>[]),...await Deno.resolveDns(h,"AAAA").catch(()=>[])];if(!ips.length||ips.some((ip:string)=>isPrivateV4(ip)||isPrivateV6(ip)))throw new Error("Feed host did not resolve to a public address.")}}
async function safeFetch(input:string,maxBytes=1_500_000){let u=new URL(input);for(let i=0;i<5;i++){await assertPublic(u);const c=new AbortController(),t=setTimeout(()=>c.abort(),10_000);let r:Response;try{r=await fetch(u,{signal:c.signal,redirect:"manual",headers:{"User-Agent":"MorningReader/1.0 (+https://morning-reader.vercel.app)"}})}finally{clearTimeout(t)}if([301,302,303,307,308].includes(r.status)){const l=r.headers.get("location");if(!l)break;u=new URL(l,u);continue}if(!r.ok)throw new Error(`Feed returned HTTP ${r.status}`);return(await r.text()).slice(0,maxBytes)}throw new Error("Too many redirects.")}
export async function probe(url:string){const x=await safeFetch(url);if(!/(<rss\b|<feed\b|<rdf:RDF\b)/i.test(x))throw new Error("That URL did not look like an RSS or Atom feed.");const m=x.match(/<title(?:\s[^>]*)?>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i);return{title:(m?.[1]||"").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").trim().slice(0,120)}}
function arr(x:any){return x==null?[]:Array.isArray(x)?x:[x]}
function text(x:any):string{if(x==null)return"";if(typeof x==="string"||typeof x==="number")return String(x);if(typeof x==="object"){if("__cdata"in x)return text(x.__cdata);if("#text"in x)return text(x["#text"])}return""}
function link(x:any):string{if(typeof x==="string")return x;for(const v of arr(x)){if(typeof v==="string")return v;if(v&&typeof v==="object"&&v["@_href"])return String(v["@_href"])}return""}
export async function preview(feed:any){try{const raw=await safeFetch(feed.url);const p=new XMLParser({ignoreAttributes:false,attributeNamePrefix:"@_",textNodeName:"#text",cdataPropName:"__cdata"}),d:any=p.parse(raw);let es:any[]=[];if(d?.rss?.channel?.item)es=arr(d.rss.channel.item);else if(d?.feed?.entry)es=arr(d.feed.entry);else if(d?.["rdf:RDF"]?.item)es=arr(d["rdf:RDF"].item);const items=es.slice(0,10).map(e=>{const raw=text(e.pubDate||e.published||e.updated||e["dc:date"]),dt=raw?new Date(raw):null;return{title:text(e.title).replace(/<[^>]+>/g,"").trim()||"Untitled",url:link(e.link)||text(e.guid||e.id),published_at:dt&&!isNaN(+dt)?dt.toISOString():null,source:feed.name}}).filter(x=>x.url);await admin.from("feeds").update({last_fetch_at:new Date().toISOString(),last_error:null}).eq("id",feed.id);return{feed_id:feed.id,items}}catch(e){const m=e instanceof Error?e.message:String(e);await admin.from("feeds").update({last_fetch_at:new Date().toISOString(),last_error:m.slice(0,500)}).eq("id",feed.id);return{feed_id:feed.id,items:[],error:m}}}
export function emailConfigured(){return Boolean(RESEND_API_KEY)}